name: "gha-test"

on:
  push:
    branches:
      - feature/workflows-test
    path:
      - aws/**
      - github/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World"